name: base
channels:
  - conda-forge
dependencies:
  - ase =3.29.0
  - assyst =0.16.0  # [unix]
  - atomistics =0.3.8
  - calphy =2.0.0  # [unix]
  - custodian =2025.12.14
  - executorlib =1.10.1
  - flux-core =0.87.0  # [linux]
  - flux-pmix =0.7.1  # [linux]
  - grace-tensorpotential =0.6.0  # [linux]
  - graphviz =14.1.2 
  - iprpy-data =2025.01.14
  - jupyterlab =4.6.2
  - lammps =2025.07.22=*openmpi*  # [unix]
  - lammpsparser =0.0.7
  - landau =1.11.0
  - lxml =6.1.1
  - matplotlib-base =3.11.1
  - mpi4py =4.1.2
  - nglview =4.0.1
  - phono3py =4.4.0
  - pygraphviz =1.14
  - pylammpsmpi =0.5.0
  - pysqa =0.4.4
  - python =3.12.13
  - python-ace =0.3.1 # [linux]
  - pyxtal =1.1.4
  - seaborn =0.13.2
  - setuptools =79.0.1 
  - sqsgenerator =0.5.6
  - tensorflow =2.19.1  # [linux]
