name: linux-x64

on:
  pull_request:

jobs:
  test_environment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: convert
      shell: bash -l {0}
      run: |
        ./.ci_support/convert_linux.sh
        cat environment.yml
        echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: environment.yml

  build_environment:
    needs: [test_environment]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
        environment-file: .ci_support/environment.yml
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 30
      run: |
        ./.ci_support/convert_linux.sh
        cat environment.yml
        python .ci_support/dryrun.py environment.yml env-linux-x64.yml 
    - uses: actions/upload-artifact@v4
      with:
        path: env-linux-x64.yml

  build_constructor:
    needs: [test_environment]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.12"
        miniforge-version: latest
        condarc-file: .condarc
    - name: Build Constructor
      shell: bash -l {0}
      run: |
        conda install -y --name test -c conda-forge constructor
        mkdir build
        ./.ci_support/convert_linux.sh
        cat environment.yml
        constructor -v --output-dir=build --platform="linux-64" constructor
